services:
  analyzer-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./database:/app/database
      - ./docs:/app/docs
    env_file:
      - .env